//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEPSMOVEinfo
    {
        public int Idno { get; set; }
        public string Userid { get; set; }
        public string ApiName1 { get; set; }
        public string ApiName2 { get; set; }
        public Nullable<bool> Status1 { get; set; }
        public Nullable<bool> Status2 { get; set; }
        public string UPIApiName1 { get; set; }
        public string UPIApiName2 { get; set; }
        public Nullable<bool> UPIStatus1 { get; set; }
        public Nullable<bool> UPIStatus2 { get; set; }
    }
}
