//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDocument
    {
        public int Id { get; set; }
        public long LoanApplicationId { get; set; }
        public string DocumentType { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string VerificationStatus { get; set; }
        public string VerificationRemarks { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public Nullable<long> UploadedBy { get; set; }
        public Nullable<long> VerifiedBy { get; set; }
    
        public virtual LoanApplication LoanApplication { get; set; }
    }
}
