//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanApplication()
        {
            this.LoanFollowUps = new HashSet<LoanFollowUp>();
            this.LoanNotes = new HashSet<LoanNote>();
            this.LoanStatusHistories = new HashSet<LoanStatusHistory>();
            this.LoanVehicles = new HashSet<LoanVehicle>();
            this.LoanDocuments = new HashSet<LoanDocument>();
            this.LoanExistingDetails = new HashSet<LoanExistingDetail>();
        }
    
        public long Id { get; set; }
        public string Retailerid { get; set; }
        public string ApplicationNo { get; set; }
        public int LoanTypeId { get; set; }
        public string FullName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string PAN { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
        public string EmploymentType { get; set; }
        public string CompanyName { get; set; }
        public Nullable<decimal> WorkExperienceYears { get; set; }
        public Nullable<decimal> MonthlyIncome { get; set; }
        public Nullable<decimal> OtherMonthlyIncome { get; set; }
        public Nullable<decimal> ExistingEMI { get; set; }
        public Nullable<int> ExistingLoans { get; set; }
        public decimal LoanAmount { get; set; }
        public Nullable<int> TenureMonths { get; set; }
        public string LoanPurpose { get; set; }
        public string Status { get; set; }
        public Nullable<long> AssignedTo { get; set; }
        public string Remarks { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<decimal> ApprovedAmount { get; set; }
        public Nullable<int> ApprovedTenureMonths { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public Nullable<System.DateTime> DisbursedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CaseType { get; set; }
        public string RefinanceType { get; set; }
        public Nullable<int> CIBILScore { get; set; }
        public Nullable<decimal> NetMonthlyIncome { get; set; }
        public Nullable<decimal> ABB { get; set; }
        public Nullable<decimal> ITRIncome { get; set; }
        public Nullable<int> Last3MonthsBounceCount { get; set; }
        public Nullable<int> BankStatementMonths { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
    
        public virtual LoanType LoanType { get; set; }
        public virtual Retailer_Details Retailer_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanFollowUp> LoanFollowUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanNote> LoanNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanStatusHistory> LoanStatusHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanVehicle> LoanVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanDocument> LoanDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanExistingDetail> LoanExistingDetails { get; set; }
    }
}
