//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanStatusHistory
    {
        public long Id { get; set; }
        public long LoanApplicationId { get; set; }
        public string OldStatus { get; set; }
        public string NewStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> ChangedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
    
        public virtual LoanApplication LoanApplication { get; set; }
    }
}
