//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanVehicle
    {
        public long Id { get; set; }
        public long LoanApplicationId { get; set; }
        public string VehicleType { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Variant { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<int> ManufacturingYear { get; set; }
        public Nullable<int> RegistrationYear { get; set; }
        public string FuelType { get; set; }
        public string Transmission { get; set; }
        public string OwnerNumber { get; set; }
        public Nullable<decimal> OnRoadPrice { get; set; }
        public Nullable<decimal> EstimatedCarValue { get; set; }
        public Nullable<decimal> DownPayment { get; set; }
        public string DealerName { get; set; }
        public string DealerMobile { get; set; }
        public string DealerLocation { get; set; }
        public string SellerName { get; set; }
        public string SellerMobile { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ManufacturingMonth { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> KMDriven { get; set; }
        public Nullable<decimal> MarketValue { get; set; }
    
        public virtual LoanApplication LoanApplication { get; set; }
    }
}
