//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanFollowUp
    {
        public long Id { get; set; }
        public long LoanApplicationId { get; set; }
        public System.DateTime FollowUpDate { get; set; }
        public string FollowUpType { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> NextFollowUpDate { get; set; }
        public string FollowUpStatus { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual LoanApplication LoanApplication { get; set; }
    }
}
