//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slab_IndoNepal
    {
        public int idno { get; set; }
        public string UserId { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
        public decimal min { get; set; }
        public decimal max { get; set; }
        public decimal charge { get; set; }
        public decimal margin { get; set; }
        public decimal gst { get; set; }
        public decimal tds { get; set; }
    }
}
