//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vastwebmulti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletToBankAmountTransferCharge
    {
        public int Idno { get; set; }
        public decimal AmtFromTatkal { get; set; }
        public Nullable<decimal> AmtToTatkal { get; set; }
        public decimal chargeTatkal { get; set; }
        public decimal TimeTakesTatkal { get; set; }
        public bool IsEnabled { get; set; }
        public string ChargeType { get; set; }
        public string UserRole { get; set; }
        public Nullable<decimal> chargeTatkalNEFT { get; set; }
        public string userid { get; set; }
    }
}
